// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateGitCommit(arg1:string,arg2:string,arg3:string):Promise<models.Commit>;

export function GetAvailableModels(arg1:string):Promise<Array<string>>;

export function GetAvailableProviders():Promise<Array<string>>;

export function GetDiffCommit(arg1:string):Promise<models.Diff>;

export function GetDiffWorkingTree():Promise<models.Diff>;

export function GetGitLog(arg1:number,arg2:number):Promise<models.CommitList>;

export function GetGitStatus():Promise<models.Status>;

export function GetRecentRepos(arg1:number):Promise<Array<models.RepoMetadata>>;

export function GetSettings():Promise<models.Settings>;

export function GetUIState():Promise<models.UIState>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<string>>;

export function ProposePatch(arg1:string):Promise<models.PatchProposal>;

export function SafeReadFile(arg1:string):Promise<string>;

export function SafeWriteFile(arg1:string,arg2:string):Promise<void>;

export function SaveUIState(arg1:models.UIState):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetGitRepository(arg1:string):Promise<void>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowInfo(arg1:string,arg2:string):Promise<void>;

export function StartChatMessage(arg1:string,arg2:string):Promise<any>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
