// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGitCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGitCommit'](arg1, arg2, arg3);
}

export function GetAvailableModels(arg1) {
  return window['go']['main']['App']['GetAvailableModels'](arg1);
}

export function GetAvailableProviders() {
  return window['go']['main']['App']['GetAvailableProviders']();
}

export function GetDiffCommit(arg1) {
  return window['go']['main']['App']['GetDiffCommit'](arg1);
}

export function GetDiffWorkingTree() {
  return window['go']['main']['App']['GetDiffWorkingTree']();
}

export function GetGitLog(arg1, arg2) {
  return window['go']['main']['App']['GetGitLog'](arg1, arg2);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetRecentRepos(arg1) {
  return window['go']['main']['App']['GetRecentRepos'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUIState() {
  return window['go']['main']['App']['GetUIState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ProposePatch(arg1) {
  return window['go']['main']['App']['ProposePatch'](arg1);
}

export function SafeReadFile(arg1) {
  return window['go']['main']['App']['SafeReadFile'](arg1);
}

export function SafeWriteFile(arg1, arg2) {
  return window['go']['main']['App']['SafeWriteFile'](arg1, arg2);
}

export function SaveUIState(arg1) {
  return window['go']['main']['App']['SaveUIState'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetGitRepository(arg1) {
  return window['go']['main']['App']['SetGitRepository'](arg1);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowInfo(arg1, arg2) {
  return window['go']['main']['App']['ShowInfo'](arg1, arg2);
}

export function StartChatMessage(arg1, arg2) {
  return window['go']['main']['App']['StartChatMessage'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
